spring:
  application:
    name: "accounts"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: "optional:configserver:http://localhost:8071"
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html