spring:
  application:
    name: accounts
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    username: ${db_username}
    password: ${db_password}
    url: ${db_url}
server:
  port: 8080
